//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegundoBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int PagIDAlu { get; set; }
        public int PagData { get; set; }
        public int PagID { get; set; }
    }
}
