//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegundoBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public Pagamento()
        {
            this.Taxa = new HashSet<Taxa>();
        }
    
        public int PagIDAlu { get; set; }
        public int PagData { get; set; }
        public int PagID { get; set; }
    
        public virtual Alguel Alguel { get; set; }
        public virtual ICollection<Taxa> Taxa { get; set; }
    }
}
