//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegundoBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxa
    {
        public int TaxaID { get; set; }
        public string TaxaNome { get; set; }
        public int TaxaValor { get; set; }
        public int TaxaIDPagamento { get; set; }
    
        public virtual Pagamento Pagamento { get; set; }
    }
}
